# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf64e3db7e54d1371ce0ce717d732d0bdd8b5e60a2cfbb37a5f34885720017fe23a066d394e8aecaf0e9537afcb8dfaedc6b42918993b63c22bd7ab345ad8a2

test:
  secret_key_base: 6555a27f0fc1a4bfa7d276b2e92baff135e8378558905f588d0585a545aeb8def9a3254606e25638c20423b0e00f10f28ba9605e60822a9923b37b5119b410bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
